controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - robotiq_2f140_left_outer_knuckle_joint
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
initial:  # Define initial robot poses per group
  - group: gripper
    pose: open
  - group: manipulator
    pose: home
