eef_gripper:
   # KDL
   # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
   # kinematics_solver_search_resolution: 0.005
   # kinematics_solver_timeout: 0.005

   # Trac-IK
   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
   kinematics_solver_search_resolution: 0.005
   kinematics_solver_timeout: 0.05

   # BioIK
   # kinematics_solver: bio_ik/BioIKKinematicsPlugin
   # kinematics_solver_search_resolution: 0.005
   # kinematics_solver_timeout: 0.005
   # kinematics_solver_attempts: 1


eef_pipette:
   # KDL
   # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
   # kinematics_solver_search_resolution: 0.005
   # kinematics_solver_timeout: 0.005

   # Trac-IK
   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
   kinematics_solver_search_resolution: 0.005
   kinematics_solver_timeout: 0.05

   # BioIK
   # kinematics_solver: bio_ik/BioIKKinematicsPlugin
   # kinematics_solver_search_resolution: 0.005
   # kinematics_solver_timeout: 0.005
   # kinematics_solver_attempts: 1
